
import os, re, hashlib
from datetime import datetime, timezone
from urllib.parse import urljoin

import requests
import feedparser
from bs4 import BeautifulSoup
from flask import Flask, jsonify, render_template, request
from apscheduler.schedulers.background import BackgroundScheduler
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError

APP_DIR = os.path.dirname(os.path.abspath(__file__))
DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    local_db = os.environ.get("DATABASE_PATH", os.path.join(APP_DIR, "leads.db"))
    DATABASE_URL = f"sqlite:///{local_db}"

# Some providers still issue postgres:// URLs; SQLAlchemy expects postgresql://.
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

SYNC_MINUTES = int(os.environ.get("SYNC_MINUTES", "30"))
USER_AGENT = os.environ.get("USER_AGENT", "OnePlugLeadHub/1.1 (+business lead monitoring)")

engine_kwargs = {"pool_pre_ping": True}
if DATABASE_URL.startswith("sqlite:"):
    engine_kwargs["connect_args"] = {"check_same_thread": False}
engine = create_engine(DATABASE_URL, future=True, **engine_kwargs)

app = Flask(__name__)

EV_TERMS = [
    "ev charging", "electric vehicle charging", "ev charger", "charging station",
    "charge point", "charging infrastructure", "cpo", "fast charger"
]
INTENT_TERMS = [
    "tender", "rfp", "eoi", "expression of interest", "requirement", "required",
    "looking for", "seeking", "partner", "install", "installation", "establish",
    "operate", "maintain", "bid", "auction", "procurement", "supply"
]
PRIORITY_LOCATIONS = [
    "tamil nadu", "coimbatore", "chennai", "salem", "trichy", "tiruchirappalli",
    "madurai", "hosur", "krishnagiri", "vellore", "erode", "tiruppur",
    "karnataka", "bengaluru", "bangalore", "mysuru", "mysore", "tumakuru"
]

def rows_as_dicts(result):
    return [dict(r) for r in result.mappings().all()]

def init_db():
    statements = [
        """
        CREATE TABLE IF NOT EXISTS leads (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            uid TEXT UNIQUE NOT NULL,
            title TEXT NOT NULL,
            company TEXT DEFAULT '',
            location TEXT DEFAULT '',
            category TEXT DEFAULT '',
            intent TEXT DEFAULT '',
            priority TEXT DEFAULT 'B',
            status TEXT DEFAULT 'New',
            source_name TEXT DEFAULT '',
            source_url TEXT DEFAULT '',
            lead_url TEXT NOT NULL,
            published_at TEXT DEFAULT '',
            deadline TEXT DEFAULT '',
            notes TEXT DEFAULT '',
            created_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS sources (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            url TEXT UNIQUE NOT NULL,
            source_type TEXT NOT NULL DEFAULT 'rss',
            enabled INTEGER NOT NULL DEFAULT 1,
            last_sync TEXT DEFAULT '',
            last_result TEXT DEFAULT ''
        )
        """
    ]
    # SQLite does not support the Postgres identity syntax, so use compatible DDL locally.
    if DATABASE_URL.startswith("sqlite:"):
        statements = [
            statements[0].replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT"),
            statements[1].replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        ]
    with engine.begin() as conn:
        for stmt in statements:
            conn.execute(text(stmt))
    seed()

def seed():
    seeds = [
        {
            "title":"Establish, operate & maintain EV charging point — Coimbatore Railway Station",
            "company":"Southern Railway",
            "location":"Coimbatore, Tamil Nadu",
            "category":"Tender / Railway",
            "intent":"Operator required for EV charging point; 5-year period; 60 sq.m.",
            "priority":"A+++","status":"New","source_name":"TenderDetail",
            "source_url":"https://www.tenderdetail.com/State-tenders/tamil-nadu-tenders/ev-charging-station-tenders",
            "lead_url":"https://www.tenderdetail.com/State-tenders/tamil-nadu-tenders/ev-charging-station-tenders",
            "deadline":"2026-10-20",
            "notes":"Verify tender documents and eligibility before bidding."
        },
        {
            "title":"Establish, operate & maintain EV charging point — Elamanur Railway Station",
            "company":"Southern Railway","location":"Elamanur, Tamil Nadu",
            "category":"Tender / Railway",
            "intent":"Operator required for EV charging point; 5-year period; 100 sq.m.",
            "priority":"A+++","status":"New","source_name":"TenderDetail",
            "source_url":"https://www.tenderdetail.com/Indian-Tenders/TenderNotice/57614118/602097584a0930f76df81aefa3e13ec4",
            "lead_url":"https://www.tenderdetail.com/Indian-Tenders/TenderNotice/57614118/602097584a0930f76df81aefa3e13ec4",
            "deadline":"2026-10-08",
            "notes":"Urgent: verify current closing time and submission requirements."
        },
        {
            "title":"EV infrastructure partnership opportunity","company":"RoadNest",
            "location":"Gundlupet / South India","category":"Private Partnership",
            "intent":"Publicly invites EV infrastructure partners for highway hospitality network.",
            "priority":"A+++","status":"New","source_name":"RoadNest",
            "source_url":"https://roadnest.in/partners/","lead_url":"https://roadnest.in/partners/",
            "notes":"Strong private-sector highway hospitality lead."
        },
        {
            "title":"Highway recharge / wayside site partnership — Trichy","company":"PATH Recharge",
            "location":"Trichy, Tamil Nadu","category":"Travel Lounge / WSA",
            "intent":"EV charging is part of planned highway amenity offering.",
            "priority":"A++","status":"New","source_name":"PATH Recharge",
            "source_url":"https://www.pathrecharge.com/","lead_url":"https://www.pathrecharge.com/",
            "notes":"Approach as charging infrastructure/operator partner."
        },
        {
            "title":"Travel lounge expansion partnership","company":"Travlounge",
            "location":"South India","category":"Travel Lounge",
            "intent":"Highway lounge model includes EV fast charging and partner expansion.",
            "priority":"A++","status":"New","source_name":"Travlounge",
            "source_url":"https://www.travlounge.com/","lead_url":"https://www.travlounge.com/",
            "notes":"Target new locations, franchise/land partner developments and additional charging capacity."
        },
    ]
    for item in seeds:
        add_lead(item)

def uid_for(title, url):
    raw = (title.strip().lower() + "|" + url.strip().lower()).encode()
    return hashlib.sha256(raw).hexdigest()[:24]

def add_lead(x):
    title_v = (x.get("title") or "Untitled lead").strip()
    lead_url = (x.get("lead_url") or x.get("source_url") or "").strip()
    if not lead_url:
        return False
    fields = {
        "uid": uid_for(title_v, lead_url), "title": title_v,
        "company": x.get("company",""), "location": x.get("location",""),
        "category": x.get("category",""), "intent": x.get("intent",""),
        "priority": x.get("priority","B"), "status": x.get("status","New"),
        "source_name": x.get("source_name",""), "source_url": x.get("source_url",""),
        "lead_url": lead_url, "published_at": x.get("published_at",""),
        "deadline": x.get("deadline",""), "notes": x.get("notes",""),
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds")
    }
    try:
        with engine.begin() as conn:
            conn.execute(text("""
                INSERT INTO leads(uid,title,company,location,category,intent,priority,status,
                source_name,source_url,lead_url,published_at,deadline,notes,created_at)
                VALUES(:uid,:title,:company,:location,:category,:intent,:priority,:status,
                :source_name,:source_url,:lead_url,:published_at,:deadline,:notes,:created_at)
            """), fields)
        return True
    except IntegrityError:
        return False

def score_text(value):
    t = re.sub(r"\s+", " ", (value or "").lower())
    ev = sum(1 for k in EV_TERMS if k in t)
    intent = sum(1 for k in INTENT_TERMS if k in t)
    loc = sum(1 for k in PRIORITY_LOCATIONS if k in t)
    score = ev*4 + intent*2 + loc*3
    if ev == 0 or intent == 0:
        return 0, "C"
    priority = "A+++" if score >= 15 else "A++" if score >= 11 else "A+" if score >= 8 else "A" if score >= 6 else "B"
    return score, priority

def location_hint(value):
    lower = (value or "").lower()
    hits = [x for x in PRIORITY_LOCATIONS if x in lower]
    return ", ".join(dict.fromkeys(h.title() for h in hits[:3]))

def sync_rss(source):
    feed = feedparser.parse(source["url"], request_headers={"User-Agent": USER_AGENT})
    new_count = 0
    for entry in feed.entries[:100]:
        title_v = getattr(entry, "title", "") or ""
        summary = getattr(entry, "summary", "") or ""
        link = getattr(entry, "link", "") or source["url"]
        combined = BeautifulSoup(title_v + " " + summary, "html.parser").get_text(" ", strip=True)
        score, priority = score_text(combined)
        if score == 0:
            continue
        if add_lead({
            "title": title_v[:500], "location": location_hint(combined),
            "category": "Auto-discovered", "intent": combined[:900],
            "priority": priority, "source_name": source["name"],
            "source_url": source["url"], "lead_url": link,
            "published_at": getattr(entry, "published", "") or getattr(entry, "updated", ""),
            "notes": f"Auto-added from RSS. Match score: {score}. Verify requirement before outreach."
        }):
            new_count += 1
    return new_count

def sync_html(source):
    r = requests.get(source["url"], timeout=20, headers={"User-Agent": USER_AGENT})
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    new_count, seen = 0, set()
    for a in soup.find_all("a", href=True):
        href = urljoin(source["url"], a["href"])
        title_v = a.get_text(" ", strip=True)
        parent = a.parent.get_text(" ", strip=True) if a.parent else title_v
        combined = (title_v + " " + parent)[:3000]
        if not title_v or href in seen:
            continue
        seen.add(href)
        score, priority = score_text(combined)
        if score == 0:
            continue
        if add_lead({
            "title": title_v[:500], "location": location_hint(combined),
            "category": "Auto-discovered", "intent": parent[:900],
            "priority": priority, "source_name": source["name"],
            "source_url": source["url"], "lead_url": href,
            "notes": f"Auto-added from public webpage. Match score: {score}. Verify source terms and requirement."
        }):
            new_count += 1
    return new_count

def sync_all():
    with engine.connect() as conn:
        sources = rows_as_dicts(conn.execute(text("SELECT * FROM sources WHERE enabled=1")))
    total = 0
    for source in sources:
        result = ""
        try:
            if source["source_type"] == "rss":
                n = sync_rss(source)
            elif source["source_type"] == "html":
                n = sync_html(source)
            else:
                n = 0
                result = "Unsupported source type"
            total += n
            result = result or f"OK — {n} new lead(s)"
        except Exception as exc:
            result = f"Error: {str(exc)[:180]}"
        with engine.begin() as conn:
            conn.execute(text("""
                UPDATE sources SET last_sync=:last_sync, last_result=:last_result WHERE id=:id
            """), {
                "last_sync": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "last_result": result, "id": source["id"]
            })
    return total

@app.route("/")
def index():
    return render_template("index.html")

@app.get("/api/leads")
def leads():
    with engine.connect() as conn:
        rows = rows_as_dicts(conn.execute(text("SELECT * FROM leads ORDER BY id DESC")))
    return jsonify(rows)

@app.post("/api/leads")
def create_lead():
    ok = add_lead(request.get_json(force=True))
    return jsonify({"ok": ok}), 201 if ok else 409

@app.patch("/api/leads/<int:lead_id>")
def update_lead(lead_id):
    data = request.get_json(force=True)
    allowed = {"status","priority","notes","company","location","category","deadline"}
    chosen = {k:v for k,v in data.items() if k in allowed}
    if not chosen:
        return jsonify({"ok":False}), 400
    assignments = ", ".join(f"{k}=:{k}" for k in chosen)
    chosen["id"] = lead_id
    with engine.begin() as conn:
        conn.execute(text(f"UPDATE leads SET {assignments} WHERE id=:id"), chosen)
    return jsonify({"ok":True})

@app.delete("/api/leads/<int:lead_id>")
def delete_lead(lead_id):
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM leads WHERE id=:id"), {"id": lead_id})
    return jsonify({"ok":True})

@app.get("/api/sources")
def sources():
    with engine.connect() as conn:
        rows = rows_as_dicts(conn.execute(text("SELECT * FROM sources ORDER BY id DESC")))
    return jsonify(rows)

@app.post("/api/sources")
def create_source():
    d = request.get_json(force=True)
    try:
        with engine.begin() as conn:
            conn.execute(text("""
                INSERT INTO sources(name,url,source_type,enabled)
                VALUES(:name,:url,:source_type,1)
            """), {
                "name": d["name"].strip(), "url": d["url"].strip(),
                "source_type": d.get("source_type","rss")
            })
        return jsonify({"ok":True}), 201
    except IntegrityError:
        return jsonify({"ok":False,"error":"Source URL already exists"}), 409

@app.patch("/api/sources/<int:source_id>")
def update_source(source_id):
    d = request.get_json(force=True)
    enabled = 1 if d.get("enabled") else 0
    with engine.begin() as conn:
        conn.execute(text("UPDATE sources SET enabled=:enabled WHERE id=:id"),
                     {"enabled":enabled, "id":source_id})
    return jsonify({"ok":True})

@app.delete("/api/sources/<int:source_id>")
def delete_source(source_id):
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM sources WHERE id=:id"), {"id":source_id})
    return jsonify({"ok":True})

@app.post("/api/sync")
def api_sync():
    return jsonify({"ok":True, "new_leads":sync_all()})

@app.get("/health")
def health():
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return jsonify({"ok":True, "database":"connected"})
    except Exception as exc:
        return jsonify({"ok":False, "database":"error", "detail":str(exc)[:160]}), 500

init_db()

# One Gunicorn worker is used in Dockerfile, so this produces a single scheduler.
scheduler = BackgroundScheduler(daemon=True)
scheduler.add_job(sync_all, "interval", minutes=SYNC_MINUTES, id="lead_sync", replace_existing=True)
scheduler.start()

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT","8000")), debug=False)
